export const TERMINAL_PROXY_PATH = "/tmp/sandhop-terminal-proxy.cjs";

export const buildTerminalProxyScript = (
  user: string,
  pass: string,
  bind: string,
  listenPort: number,
  upstreamPort: number,
  htmlPath: string,
  session: string,
): string => {
  const expected = Buffer.from(`${user}:${pass}`).toString("base64");
  return [
    'const http = require("node:http");',
    'const net = require("node:net");',
    'const { readFileSync } = require("node:fs");',
    'const { execFile } = require("node:child_process");',
    `const EXPECTED = "Basic ${expected}";`,
    `const UPSTREAM_PORT = ${upstreamPort};`,
    `const HTML_PATH = ${JSON.stringify(htmlPath)};`,
    `const SESSION = ${JSON.stringify(session)};`,
    "// The pty keeps the size of the first client forever; /size lets later",
    "// clients render that exact grid (scaled) instead of resizing the pty,",
    "// which would garble already-rendered agent output.",
    "const sendSize = (res) => {",
    "  execFile(",
    '    "bash",',
    `    ["-lc", "tmux display -t " + SESSION + " -p '#{window_width} #{window_height}'"],`,
    "    (err, stdout) => {",
    '      res.writeHead(200, { "Content-Type": "application/json" });',
    "      if (err) {",
    "        res.end(JSON.stringify(null));",
    "        return;",
    "      }",
    '      const [cols, rows] = stdout.trim().split(" ").map(Number);',
    "      if (!Number.isFinite(cols) || !Number.isFinite(rows) || cols <= 0 || rows <= 0) {",
    "        res.end(JSON.stringify(null));",
    "        return;",
    "      }",
    "      res.end(JSON.stringify({ cols, rows }));",
    "    },",
    "  );",
    "};",
    "const server = http.createServer((req, res) => {",
    "  if (req.headers.authorization !== EXPECTED) {",
    '    res.writeHead(401, { "WWW-Authenticate": \'Basic realm="sandhop"\' });',
    "    res.end();",
    "    return;",
    "  }",
    '  const path = req.url.split("?")[0];',
    '  if (path === "/" || path === "/index.html") {',
    '    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });',
    "    res.end(readFileSync(HTML_PATH));",
    "    return;",
    "  }",
    '  if (path === "/size") {',
    "    sendSize(res);",
    "    return;",
    "  }",
    "  const up = http.request({",
    '    host: "127.0.0.1",',
    "    port: UPSTREAM_PORT,",
    "    path: req.url,",
    "    method: req.method,",
    "    headers: req.headers,",
    "  });",
    "  req.pipe(up);",
    '  up.on("response", (upRes) => {',
    "    res.writeHead(upRes.statusCode, upRes.headers);",
    "    upRes.pipe(res);",
    "  });",
    '  up.on("error", () => {',
    "    res.writeHead(502);",
    "    res.end();",
    "  });",
    "});",
    "// Safari/WebKit never sends Authorization on websocket upgrades",
    "// (WebKit bug 80362), so upgrades pass through with the header",
    "// injected; ttyd still requires the in-band AuthToken (obtainable",
    "// only via the basic-auth-gated /token endpoint) before it attaches.",
    'server.on("upgrade", (req, socket, head) => {',
    '  const up = net.connect(UPSTREAM_PORT, "127.0.0.1", () => {',
    "    const lines = [`${req.method} ${req.url} HTTP/1.1`];",
    "    for (let i = 0; i < req.rawHeaders.length; i += 2) {",
    '      if (req.rawHeaders[i].toLowerCase() === "authorization") continue;',
    "      lines.push(`${req.rawHeaders[i]}: ${req.rawHeaders[i + 1]}`);",
    "    }",
    "    lines.push(`Authorization: ${EXPECTED}`);",
    '    up.write(lines.join("\\r\\n") + "\\r\\n\\r\\n");',
    "    if (head.length > 0) up.write(head);",
    "    socket.pipe(up);",
    "    up.pipe(socket);",
    "  });",
    '  up.on("error", () => socket.destroy());',
    '  socket.on("error", () => up.destroy());',
    "});",
    `server.listen(${listenPort}, "${bind}");`,
  ].join("\n");
};
